import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
      <Sidebar/>
      <body className={inter.className}>
        {children}
      </body>
      */}
      <body>
        <div className="flex">
          <main className="flex-1 ml-16 md:ml-54 p-4">

            {children}
          </main>
        </div>
      </body>  

    </html>
  );
}
